name: Java_CI

on:
  push:
    paths:
      - 'java/**'
      - '.github/workflows/java**'
  pull_request:
    paths:
      - 'java/**'
      - '.github/workflows/java**'

jobs:

  _1_8__11_build:
    runs-on: ubuntu-16.04

    strategy:
      matrix:
        java: [ 1.8, 11 ]
    name: Java ${{ matrix.java }} junit5 sub dir Build

    steps:
      - uses: actions/checkout@v1
      - name: setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
     #### BEGIN junit5
      - name: build junit5 with maven
        working-directory: java/junit5
        run: mvn -B clean package --file pom.xml -Dtest=ThingTest\#it_should_not_fail  -Dmaven.compiler.source=${{matrix.java}} -Dmaven.compiler.target=${{matrix.java}}
      # gradle:
      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: java/junit5
          gradle-version: current
          arguments: test --warning-mode all --tests ThingTest.it_should_not_fail
      #### END junit5



  matrix_build:
    runs-on: ubuntu-16.04

    strategy:
      matrix:
        java: [ 1.8, 11, 12, 13 ]
    name: Java ${{ matrix.java }} Build

    steps:
      - uses: actions/checkout@v1
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
     #### BEGIN junit5
      - name: build junit5 with maven
        working-directory: java/junit5
        run: mvn -B clean package --file pom.xml -Dtest=ThingTest\#it_should_not_fail  -Dmaven.compiler.source=${{matrix.java}} -Dmaven.compiler.target=${{matrix.java}}
      # gradle:
      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: java/junit5
          gradle-version: current
          arguments: test --warning-mode all --tests ThingTest.it_should_not_fail
      #### END junit5

      - name: build cucumber with maven
        working-directory: java/cucumber
        run: mvn -B clean package --file pom.xml -Dmaven.compiler.source=${{matrix.java}} -Dmaven.compiler.target=${{matrix.java}}
